### ISSUE TITLE
Crash!!

### ISSUE THREAD

**Issue by bhawan0407** [danishansari/OpenLogger#1]
Please find the attached backtrace of the Crash.
![screenshot from 2016-12-13 10-11-22](https://cloud.githubusercontent.com/assets/12829084/21127995/280c594c-c11d-11e6-9eae-01f3d81cf8cf.png)

**Comment by danishansari** [comment]
Thanks for raising this issue, i'll look in to this soon.

**Comment by danishansari** [comment]
@bhawan0407 Crash is fixed now, thanks for raising it. Cheers!!
